### ISSUE TITLE
文件大小能否以GB或MB为单位显示---一个小小的请求

### ISSUE THREAD

**Issue by gao4433** [VGEAREN/webdav-caiyun#17]
**描述：**
前端文件列表中文件size以Bytes为单位显示,可阅读性较差,能否改为更人性化的单位显示

**复现：**
页面文件列表展示

**预期：**
该是怎么样的？

**截图：**
![image](https://github.com/VGEAREN/webdav-caiyun/assets/90138939/22c70d69-b137-4f38-8385-0a28afbd27bd)

**环境：**
 - Jar
 - release

**运行参数：**
-----

**Comment by VGEAREN** [comment]
感谢反馈，Commit: [7987ff7](https://github.com/VGEAREN/webdav-caiyun/commit/7987ff7)

<img width="843" alt="image" src="https://github.com/VGEAREN/webdav-caiyun/assets/16369928/4cb6f7a9-d59f-4d44-bac4-15d391759c19">
