### ISSUE TITLE
移动云盘 修改了COOKIE 相关参数名，麻烦更新一下代码和docker镜像。

### ISSUE THREAD

**Issue by falconchen** [VGEAREN/webdav-caiyun#19]
如果照原来的参数启动Docker容器会报500错误，估计是鉴权失败。

- 之前的：
![](https://txhk.cellmean.com/photo/i/2023/06/28/j5q4i2-0.png)

- 现在的：
![](https://txhk.cellmean.com/photo/i/2023/06/28/j3vhnv-0.png)

**Comment by gao4433** [comment]
我也是这样，以为token过期了，怎么改都不行😭

**Comment by VGEAREN** [comment]
已更新 [5d30271](https://github.com/VGEAREN/webdav-caiyun/commit/5d30271)
