### ISSUE TITLE
大佬 最近和彩云失效了  

### ISSUE THREAD

**Issue by xiaomumu8633** [VGEAREN/webdav-caiyun#3]
**描述：**
请清晰的描述是什么样的BUG

**复现：**
复现下BUG怎么出现的

**预期：**
该是怎么样的？

**截图：**

**环境：**
 - 运行方式？Jar？Docker？
 - 版本？

**运行参数：**
最好能把运行参数贴出来

**Comment by VGEAREN** [comment]
@xiaomumu8633 token失效了……用网页版的最新token替换即可。不知道是不是和彩云统一失效了token，还是说token到一定时间必然会失效，我抽时间研究下账号密码的登录方式吧。
