### ISSUE TITLE
大佬，Mac系统中用docker-compose挂载为本地盘后，无法打开.jpg文件，也无法拷贝.jpg文件，但是能打开.docx文件

### ISSUE THREAD

**Issue by mpeng819** [VGEAREN/webdav-caiyun#4]
直接双击打开5G.jpg：
![Screen Shot 2022-02-18 at 11 02 18 PM](https://user-images.githubusercontent.com/8943048/154708411-9b6b6af7-8bb8-4bf9-bc29-bbb65d0a10da.png)

尝试将文件copy到desktop：
![Screen Shot 2022-02-18 at 11 02 38 PM](https://user-images.githubusercontent.com/8943048/154708469-eb7f57e1-44ee-4009-ad87-36e1230ca0de.png)

部分错误信息输出：

caiyun-webdav    | 2022-02-18 23:09:21.782  INFO 1 --- [nio-8080-exec-1] c.v.w.store.CaiyunDriverFileSystemStore  : getStoredObject: /5G.jpg
caiyun-webdav    | 2022-02-18 23:09:21.784  INFO 1 --- [nio-8080-exec-1] c.v.w.store.CaiyunDriverFileSystemStore  : getStoredObject: /5G.jpg
caiyun-webdav    | 2022-02-18 23:09:21.784  INFO 1 --- [nio-8080-exec-1] c.v.w.store.CaiyunDriverFileSystemStore  : getStoredObject: /5G.jpg
caiyun-webdav    | 2022-02-18 23:09:21.795  INFO 1 --- [nio-8080-exec-9] c.v.w.store.CaiyunDriverFileSystemStore  : getStoredObject: /5G.jpg
caiyun-webdav    | 2022-02-18 23:09:21.797  INFO 1 --- [nio-8080-exec-9] c.v.w.store.CaiyunDriverFileSystemStore  : getStoredObject: /5G.jpg
caiyun-webdav    | 2022-02-18 23:09:21.800  INFO 1 --- [nio-8080-exec-9] c.v.w.store.CaiyunDriverFileSystemStore  : getStoredObject: /5G.jpg
caiyun-webdav    | 2022-02-18 23:09:21.804  INFO 1 --- [nio-8080-exec-9] c.v.w.store.CaiyunDriverFileSystemStore  : getResourceContent: /5G.jpg
caiyun-webdav    | 2022-02-18 23:09:21.911  WARN 1 --- [nio-8080-exec-8] net.sf.webdav.methods.DoGet              : /5G.jpg Flushing OutputStream causes Exception!
caiyun-webdav    |
caiyun-webdav    |
caiyun-webdav    | org.apache.catalina.connector.ClientAbortException: java.io.IOException: Broken pipe
caiyun-webdav    | 	at org.apache.catalina.connector.OutputBuffer.realWriteBytes(OutputBuffer.java:353) ~[tomcat-embed-core-9.0.55.jar!/:na]
caiyun-webdav    | 	at org.apache.catalina.connector.OutputBuffer.flushByteBuffer(OutputBuffer.java:783) ~[tomcat-embed-core-9.0.55.jar!/:na]
caiyun-webdav    | 	at org.apache.catalina.connector.OutputBuffer.doFlush(OutputBuffer.java:299) ~[tomcat-embed-core-9.0.55.jar!/:na]
caiyun-webdav    | 	at org.apache.catalina.connector.OutputBuffer.flush(OutputBuffer.java:273) ~[tomcat-embed-core-9.0.55.jar!/:na]
caiyun-webdav    | 	at org.apache.catalina.connector.CoyoteOutputStream.flush(CoyoteOutputStream.java:118) ~[tomcat-embed-core-9.0.55.jar!/:na]
caiyun-webdav    | 	at net.sf.webdav.methods.DoGet.doBody(DoGet.java:84) ~[classes!/:1.0.0]
caiyun-webdav    | 	at net.sf.webdav.methods.DoHead.execute(DoHead.java:156) ~[classes!/:1.0.0]
caiyun-webdav    | 	at net.sf.webdav.WebDavServletBean.service(WebDavServletBean.java:131) ~[classes!/:1.0.0]
caiyun-webdav    | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764) ~[tomcat-embed-core-9.0.55.jar!/:na]
caiyun-webdav    | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227) ~[tomcat-embed-core-9.0.55.jar!/:na]
caiyun-webdav    | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.55.jar!/:na]
caiyun-webdav    | 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-embed-websocket-9.0.55.jar!/:na]
caiyun-webdav    | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.55.jar!/:na]
caiyun-webdav    | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.55.jar!/:na]
caiyun-webdav    | 	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-5.3.13.jar!/:5.3.13]
caiyun-webdav    | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.3.13.jar!/:5.3.13]
caiyun-webdav    | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.55.jar!/:na]
caiyun-webdav    | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.55.jar!/:na]
caiyun-webdav    | 	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[spring-web-5.3.13.jar!/:5.3.13]
caiyun-webdav    | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.3.13.jar!/:5.3.13]
caiyun-webdav    | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.55.jar!/:na]
caiyun-webdav    | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.55.jar!/:na]
caiyun-webdav    | 	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-5.3.13.jar!/:5.3.13]
caiyun-webdav    | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.3.13.jar!/:5.3.13]
caiyun-webdav    | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.55.jar!/:na]
caiyun-webdav    | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.55.jar!/:na]
caiyun-webdav    | 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197) ~[tomcat-embed-core-9.0.55.jar!/:na]
caiyun-webdav    | 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) ~[tomcat-embed-core-9.0.55.jar!/:na]
caiyun-webdav    | 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:659) ~[tomcat-embed-core-9.0.55.jar!/:na]
caiyun-webdav    | 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:659) ~[tomcat-embed-core-9.0.55.jar!/:na]
caiyun-webdav    | 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135) ~[tomcat-embed-core-9.0.55.jar!/:na]
caiyun-webdav    | 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) ~[tomcat-embed-core-9.0.55.jar!/:na]
caiyun-webdav    | 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) ~[tomcat-embed-core-9.0.55.jar!/:na]
caiyun-webdav    | 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357) ~[tomcat-embed-core-9.0.55.jar!/:na]
caiyun-webdav    | 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:382) ~[tomcat-embed-core-9.0.55.jar!/:na]
caiyun-webdav    | 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) ~[tomcat-embed-core-9.0.55.jar!/:na]
caiyun-webdav    | 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:895) ~[tomcat-embed-core-9.0.55.jar!/:na]
caiyun-webdav    | 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1722) ~[tomcat-embed-core-9.0.55.jar!/:na]
caiyun-webdav    | 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-embed-core-9.0.55.jar!/:na]
caiyun-webdav    | 	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[tomcat-embed-core-9.0.55.jar!/:na]
caiyun-webdav    | 	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[tomcat-embed-core-9.0.55.jar!/:na]
caiyun-webdav    | 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-9.0.55.jar!/:na]
caiyun-webdav    | 	at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]
caiyun-webdav    | Caused by: java.io.IOException: Broken pipe
caiyun-webdav    | 	at java.base/sun.nio.ch.FileDispatcherImpl.write0(Native Method) ~[na:na]
caiyun-webdav    | 	at java.base/sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47) ~[na:na]
caiyun-webdav    | 	at java.base/sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:113) ~[na:na]
caiyun-webdav    | 	at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:79) ~[na:na]
caiyun-webdav    | 	at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:50) ~[na:na]
caiyun-webdav    | 	at java.base/sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:462) ~[na:na]
caiyun-webdav    | 	at org.apache.tomcat.util.net.NioChannel.write(NioChannel.java:135) ~[tomcat-embed-core-9.0.55.jar!/:na]
caiyun-webdav    | 	at org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper.doWrite(NioEndpoint.java:1363) ~[tomcat-embed-core-9.0.55.jar!/:na]
caiyun-webdav    | 	at org.apache.tomcat.util.net.SocketWrapperBase.doWrite(SocketWrapperBase.java:766) ~[tomcat-embed-core-9.0.55.jar!/:na]
caiyun-webdav    | 	at org.apache.tomcat.util.net.SocketWrapperBase.writeBlocking(SocketWrapperBase.java:586) ~[tomcat-embed-core-9.0.55.jar!/:na]
caiyun-webdav    | 	at org.apache.tomcat.util.net.SocketWrapperBase.write(SocketWrapperBase.java:530) ~[tomcat-embed-core-9.0.55.jar!/:na]
caiyun-webdav    | 	at org.apache.coyote.http11.Http11OutputBuffer$SocketOutputBuffer.doWrite(Http11OutputBuffer.java:547) ~[tomcat-embed-core-9.0.55.jar!/:na]
caiyun-webdav    | 	at org.apache.coyote.http11.filters.IdentityOutputFilter.doWrite(IdentityOutputFilter.java:73) ~[tomcat-embed-core-9.0.55.jar!/:na]
caiyun-webdav    | 	at org.apache.coyote.http11.Http11OutputBuffer.doWrite(Http11OutputBuffer.java:194) ~[tomcat-embed-core-9.0.55.jar!/:na]
caiyun-webdav    | 	at org.apache.coyote.Response.doWrite(Response.java:615) ~[tomcat-embed-core-9.0.55.jar!/:na]
caiyun-webdav    | 	at org.apache.catalina.connector.OutputBuffer.realWriteBytes(OutputBuffer.java:340) ~[tomcat-embed-core-9.0.55.jar!/:na]
caiyun-webdav    | 	... 42 common frames omitted
caiyun-webdav    |
caiyun-webdav    | 2022-02-18 23:09:21.920  WARN 1 --- [nio-8080-exec-8] net.sf.webdav.methods.DoGet              : /5G.jpg doBody causes Exception!

**Comment by VGEAREN** [comment]
Fix in [26627d9](https://github.com/VGEAREN/webdav-caiyun/commit/26627d9d6c5eb901813463d3f87fe2a7cc9fb356)
