### ISSUE TITLE
感谢大神。

### ISSUE THREAD

**Issue by ymkfssy** [VGEAREN/webdav-caiyun#7]
感谢大神。这个很好用。
我的群辉挂载成功了
https://www.hundun.live/2022/04/03/%e7%be%a4%e8%be%89nas%e5%bc%80%e5%90%af%e5%92%8c%e5%bd%a9%e4%ba%91webdav%e5%90%8c%e6%ad%a5%e6%96%87%e4%bb%b6%e5%a4%b9%ef%bc%8c%e5%a6%82%e4%bd%95%e4%bc%98%e9%9b%85%e7%9a%84%e8%96%85%e7%a7%bb%e5%8a%a8/

**Comment by VGEAREN** [comment]
感谢支持～😊
